apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: rest-service-db
  namespace: accelerator-system
spec:
  git:
    url: ssh://git@github.com/pivotal/acc-content
    ref:
      branch: feature/rest-api-db
    subPath: rest-service-db
    secretRef:
      name: vmware-jaret-credentials
